//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod exercise;
pub mod exercise_muscle;
pub mod gym;
pub mod gym_profile;
pub mod muscle;
pub mod profile;
pub mod program;
pub mod program_target_muscle;
pub mod seed;
pub mod set;
pub mod target_muscle;
pub mod workout;
