//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::exercise::Entity as Exercise;
pub use super::exercise_muscle::Entity as ExerciseMuscle;
pub use super::gym::Entity as Gym;
pub use super::gym_user::Entity as GymUser;
pub use super::muscle::Entity as Muscle;
pub use super::program::Entity as Program;
pub use super::program_target_muscle::Entity as ProgramTargetMuscle;
pub use super::set::Entity as Set;
pub use super::target_muscle::Entity as TargetMuscle;
pub use super::user::Entity as User;
pub use super::workout::Entity as Workout;
