[package]
name = "db"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
sea-orm-migration = { workspace = true }
sea-orm = { workspace = true }
tracing = { workspace = true }
