//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::exercise::Entity as Exercise;
pub use super::exercise_muscle::Entity as ExerciseMuscle;
pub use super::gym::Entity as Gym;
pub use super::gym_profile::Entity as GymProfile;
pub use super::muscle::Entity as Muscle;
pub use super::profile::Entity as Profile;
pub use super::session::Entity as Session;
pub use super::set::Entity as Set;
pub use super::workout::Entity as Workout;
